---

  - name: Install Modoboa packages
    apt:
      pkg: '{{ item }}'
      state: 'present'
      install_recommends: 'no'
    with_flattened:
      - [ 'apache2', 'libapache2-mod-wsgi', 'python-pip', 'python-rrdtool', 'python-dev' ]
      - [ 'libcairo2-dev', 'librrd-dev', 'libxml2-dev', 'libxslt-dev', 'zlib1g-dev' ]
      - [ '{{ "python-mysqldb" if "mysql" in modoboa_sql_driver else [] }}' ]

  - name: Install Dovecot packages
    apt:
      pkg: '{{ item }}'
      state: 'present'
      install_recommends: 'no'
    with_flattened:
      - [ '{{ "dovecot-mysql" if "mysql" in modoboa_sql_driver else [] }}' ]

  - name: Install Postfix packages
    apt:
      pkg: '{{ item }}'
      state: 'present'
      install_recommends: 'no'
    with_flattened:
      - [ '{{ "postfix-mysql" if "mysql" in modoboa_sql_driver else [] }}' ]

  # - name: download modoboa
  #   get_url: url=https://pypi.python.org/packages/source/m/modoboa/modoboa-1.3.1.tar.gz dest=/tmp/modoboa-1.3.1.tar.gz
  #
  # - name: unarchive modoboa
  #   unarchive: src=/tmp/modoboa-1.3.1.tar.gz dest=/tmp copy=no
  #
  # - name: install modoboa
  #   shell: python setup.py install
  #   args:
  #     chdir: /tmp/modoboa-1.3.1

  - name: Install Modoboa
    pip: name=modoboa version={{modoboa_version}} state=present

  - name: Install Modoboa Plugins
    pip: name={{ item }} state=present
    with_items: modoboa_plugins

  - name: Create System Email Group
    group: name={{modoboa_system_group_name}} state=present gid={{modoboa_system_group_id}}

  - name: Create System Email User
    user: name={{modoboa_system_user_name}} state=present uid={{modoboa_system_user_id}} group={{modoboa_system_group_name}} home={{modoboa_system_mailbox_directory}} shell=/bin/false

  - name: deploy modoboa application
    shell: "modoboa-admin.py deploy {{modoboa_install_name}} --collectstatic --dburl default:{{modoboa_sql_driver}}://modoboa:{{ lookup('password', secret + '/credentials/' + ansible_fqdn + '/' + modoboa_sql_driver + '/' + modoboa_sql_dbname + '/modoboa') }}@localhost:3306/{{modoboa_sql_dbname}} --extensions {{ ' '.join(modoboa_plugins) }} --domain localhost"
    args:
      chdir: /srv
      creates: "{{modoboa_install_name}}"

  - name: Compile Modoboa wsgi.py file
    template:
      src: '{{ lookup("template_src", "wsgi.py.j2") }}'
      dest: '{{modoboa_home}}/{{modoboa_install_name}}/wsgi.py'

  - name: Apache | Enable required Apache modules
    apache2_module: state=present name={{ item }}
    with_items:
      - wsgi
      - ssl

  - name: Apache | Disable the default site
    action: command a2dissite 000-default
    ignore_errors: yes
    tags: apache

  - name: Apache | Compile Apache Modoboa configuration
    template:
      src: '{{ lookup("template_src", "apache.conf.j2") }}'
      dest: '/etc/apache2/sites-available/modoboa.conf'
    tags: apache

  - name: Apache | Enable our Modoboa site
    action: command a2ensite modoboa
    sudo: yes
    tags: apache
    notify:
      - apache restart

  - name: Generate Postfix Map Files
    shell: "modoboa-admin.py postfix_maps --extensions {{ ' '.join(modoboa_plugins) }} --dburl {{modoboa_sql_driver}}://{{modoboa_sql_username}}:{{ lookup('password', secret + '/credentials/' + ansible_fqdn + '/' + modoboa_sql_driver + '/' + modoboa_sql_dbname + '/modoboa') }}@127.0.0.1:3306/{{modoboa_sql_dbname}} /etc/postfix/maps"
    args:
      chdir: /srv
      creates: /etc/postfix/maps

  # CUSTOM DOVECOT CONFIGURATION FOR MODOBOA
  - name: Create before.d for sieve
    file:
      path: '{{modoboa_system_mailbox_directory}}/sieve/before.d'
      state: 'directory'
      mode: 0770
      owner: 'root'
      group: '{{modoboa_system_group_name}}'

  - name: Generate junk email sieve script
    template:
      src: '{{ lookup("template_src", "sieve/00-spam.sieve.j2") }}'
      dest: '{{modoboa_system_mailbox_directory}}/sieve/before.d/00-spam.sieve'

  - name: Assign or Generate Dovecot SQL Password
    set_fact: modoboa_dovecot_sql_password='{{ lookup("password", secret + "/credentials/" + ansible_fqdn + "/" + modoboa_sql_driver + "/" + modoboa_sql_dbname + "/" + modoboa_dovecot_sql_username + " length=" + modoboa_sql_password_length) }}'
    when: "'sql' in modoboa_dovecot_user_accounts"

  - name: Generate Dovecot SQL Configuration
    template:
      src: "{{ lookup('template_src', 'etc/dovecot/dovecot-sql.conf.ext.j2') }}"
      dest: '/etc/dovecot/dovecot-sql.conf.ext'
      mode: '0640'
      owner: 'root'
      group: 'dovecot'
      force: yes
    when: "'sql' in modoboa_dovecot_user_accounts"

  - name: Generate Dovecot Dictionary SQL Configuration
    template:
      src: "{{ lookup('template_src', 'etc/dovecot/dovecot-dict-sql.conf.ext.j2') }}"
      dest: '/etc/dovecot/dovecot-dict-sql.conf.ext'
      mode: '0640'
      owner: 'root'
      group: 'dovecot'
      force: yes
    when: "'sql' in modoboa_dovecot_user_accounts"

  - name: Generate dovecot configuration
    template:
      src: '{{ lookup("template_src", "etc/dovecot/conf.d/10-mail2.conf.j2") }}'
      dest: '/etc/dovecot/conf.d/10-mail2.conf'
    notify: [ 'dovecot restart' ]

  - name: Generate dovecot local.conf
    template:
      src: "{{ lookup('template_src', 'etc/dovecot/local.conf.j2') }}"
      dest: '/etc/dovecot/local.conf'
      owner: 'root'
      group: 'root'
      mode: '0644'
      force: yes
    notify: [ 'dovecot restart' ]
